pipeline {
    agent any

    environment {
        IMAGE_NAME = "fruitshop-frontend"
        IMAGE_TAG  = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Danoja936/Docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} docker-project-main/frontend/"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully! Docker image ${IMAGE_NAME}:${IMAGE_TAG} built."
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}
